[package]
name = "phaier_japanese"
version = "0.0.1"
edition = "2021"
authors = ["Toshiaki Inahata <darwin49@gmail.com>"]
description = "A library for Japanese text processing"
license = "MIT"

[features]
default = []
kana = []
roman = []
csv = []
all = ["kana", "roman", "csv"]

[dependencies]
