name: test
on:
  push:
    branches:
      - main
      - develop

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: test
        run: |
          cargo test --all-features
